apiVersion: apps/v1
kind: Deployment
metadata:
  name: savia-rer-sanita-laemur
  labels:
    app: savia-rer-sanita-laemur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: savia-rer-sanita-laemur
  template:
    metadata:
      labels:
        app: savia-rer-sanita-laemur
    spec:
      containers:
        - name: savia-rer-sanita-laemur
          image: python:3
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep"]
          args: ["infinity"]
          workingDir: "/"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1 # requesting 1 GPU
      volumes:
        - name: nvidia-driver
          hostPath:
            path: /usr/local/nvidia
            type: Directory
