apiVersion: v1
kind: Pod
metadata:
  name: rer-savia-test01
  namespace: rer-savia
spec:
  containers:
    - command: ["/bin/sh","-c"]
      args: ["           mkdir /rer_app; cd /rer_app/; git init; git remote add origin https://github.com/Peppesergee/savia-test.git;            git branch -M main; git pull origin main; cd /rer_venv; . bin/activate; pip install -r /rer_app/requirements.txt; while true; do echo ''; sleep 60; done"]
      image: https://harbor-core.prod.margherita.ad.lepida.it
      imagePullPolicy: IfNotPresent
      name: savia-test-container
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      resources:
        limits:
          nvidia.com/gpu: 2
          memory: 30Gi
          cpu: "16"
        requests:
          memory: 8Gi
          cpu: "8"
  metadata:
    namespace: rer-savia
  runtimeClassName: nvidia
